name: Lint

on:
  push:
    branches:
      - main # Change this to your default branch name

jobs:
  lint:
    name: Lint Code
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Setup Node.js and Yarn
      uses: actions/setup-node@v2
      with:
        node-version: 16 # You can change this to your preferred Node.js version

    - name: Install Yarn
      run: npm install -g yarn

    - name: Install Dependencies
      run: yarn install
  
    - name: Lint Core
      run: yarn lint
      working-directory: ./core

    - name: Lint Web
      run: yarn install && yarn lint
      working-directory: ./web

    - name: Lint Native
      run: yarn install && yarn lint
      working-directory: ./native
