name: Lint

on:
  push:
    branches:
      - main # Change this to your default branch name

jobs:
  lint:
    name: Lint Code
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Setup Node.js and Yarn
      uses: actions/setup-node@v2
      with:
        node-version: 14 # You can change this to your preferred Node.js version

    - name: Install Yarn
      run: npm install -g yarn

    - name: Install Dependencies in 'native' directory
      run: cd native && yarn install
      working-directory: ./native  # Update the path as per your project structure

    - name: Install Dependencies in 'web' directory
      run: cd web && yarn install
      working-directory: ./web  # Update the path as per your project structure
    
    - name: Lint Core
      run: yarn lint:core

    - name: Lint Web
      run: yarn lint:web

    - name: Lint Native
      run: yarn lint:native
